version: "3"
   
services:
  backend:
    container_name: backend-nas-daily
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - './:/app/'
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true